export type UserInfo = {
  "name": string;
  "given_name": string;
  "middle_name": string;
  "family_name": string;
  "nickname": string;
  "preferred_username": string;
  "profile": string;
  "picture": string;
  "website": string;
  "birthdate": string;
  "gender": "U";
  "zoneinfo": string;
  "locale": string;
  "updated_at": string;
  "tenant_id": string;
  "sub": string;
  email?: string;
  phone?: string;
};
